--- #this marks the beggining of the document, please don't add this to the sub page locales because they extend this file
htmlLang: en
meta:
  title: &meta_title Project Name
  description: &meta_description Project meta description

reduce_motion:
  on: Reduce motion
  off: Enable motion

main_skip_button: Skip to main content

main_nav:
  title: Main navigation
  menu:
    label: Menu
    open: Open navigation
    close: Close navigation
  items:
    - id: home
      href: ""
      label: Home
    - id: subpage
      href: "subpage"
      label: Sub-page

main_footer: &main_footer
  legal: &main_footer-legal
    - © 2019 we { the collective }
    - More footer content
