const BUILD_DIRECTORY = "build";
const BUILD_ASSETS_FOLDER = `${BUILD_DIRECTORY}/assets`;
const SOURCE_FOLDER = "src";
const SOURCE_WEBSITE_FOLDER = `${SOURCE_FOLDER}/website`;
const SOURCE_WEBSITE_ASSETS_FOLDER = `${SOURCE_WEBSITE_FOLDER}/assets`;

module.exports = {
  BUILD_DIRECTORY,
  SOURCE_FOLDER,
  SOURCE_WEBSITE_FOLDER,
  SOURCE_WEBSITE_ASSETS_FOLDER,
  BUILD_ASSETS_FOLDER,
};
