const BUILD_FOLDER = "build";
const BUILD_ASSETS_FOLDER = `${BUILD_FOLDER}/assets`;
const SOURCE_FOLDER = "src";
const SOURCE_WEBSITE_FOLDER = `${SOURCE_FOLDER}/website`;
const SOURCE_WEBSITE_ASSETS_FOLDER = `${SOURCE_WEBSITE_FOLDER}/assets`;

module.exports = {
  BUILD_FOLDER,
  SOURCE_FOLDER,
  SOURCE_WEBSITE_FOLDER,
  SOURCE_WEBSITE_ASSETS_FOLDER,
  BUILD_ASSETS_FOLDER
};
