# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish sweet-potato-components

on:
  push:
    branches:
      - main
    paths:
      - "components/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: "./components/.nvmrc"
          registry-url: https://registry.npmjs.org/
      - run: npm publish --access public
        working-directory: "./components"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      # Publish to GHP
      - uses: actions/setup-node@v4
        with:
          node-version-file: "./components/.nvmrc"
          registry-url: https://npm.pkg.github.com/
      - run: npm publish
        working-directory: "./components"
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
